DROP TABLE IF EXISTS delays;
CREATE TABLE delays
(
    `Financial Year & Period` VARCHAR(11),
    Date DATETIME,
    `Train ID - Affected` VARCHAR(10),
    `Planned Origin Location Code - Affected` INT(11),
    `Planned Origin GBTT Datetime - Affected` DATETIME,
    `Planned Origin WTT Datetime - Affected` DATETIME,
    `Planned Dest Location Code - Affected` INT(11),
    `Planned Dest GBTT Datetime - Affected` DATETIME,
    `Planned Dest WTT Datetime - Affected` DATETIME,
    `TSC - Affected` INT(11),
    `Service Group Code - Affected` VARCHAR(4),
    `Operator - Affected` CHAR(2),
    `English Day Type` CHAR(2),
    `Applicable Timetable Flag - Affected` CHAR(1),
    `Train Schedule Type - Affected` VARCHAR(15),
    `Traction Type - Affected` VARCHAR(3),
    `Trailing Load - Affected` INT(11),
    `Timing Load - Affected` CHAR(1),
    `Unit Class - Affected` INT(11),
    `Incident Number` INT(11),
    `Incident Create Date` DATETIME,
    `Incident Start Datetime` DATETIME,
    `Incident End Datetime` DATETIME,
    `Section Code` VARCHAR(15),
    `Network Rail Location Manager` VARCHAR(4),
    `Responsible Manager` VARCHAR(4),
    `Incident Reason` CHAR(2),
    `Attribution Status` VARCHAR(31),
    `Incident Equipment` VARCHAR(15),
    `Incident Description` VARCHAR(31),
    `Reactionary Reason Code` VARCHAR(31),
    `Incident Responsible Train` VARCHAR(15),
    `Performance Event Code` CHAR(1),
    `Start Stanox` INT(11),
    `End Stanox` INT(11),
    `Event Datetime` DATETIME,
    `PfPI Minutes` INT(11),
    `Train ID - Resp` VARCHAR(11),
    `Train ID - React` VARCHAR(15)
);
